[tasks.init]
dependencies = ["install", "link", "reload-tmux-conf"]

[tasks.install]
script = '''
sh install/install.sh
makers install-vscode-extensions
'''

[tasks.write-vscode-extensions]
cwd = "vscode/extensions"
script = '''
sh write.sh
'''

[tasks.install-vscode-extensions]
script = '''
sh vscode/extensions/install.sh
'''

[tasks.link]
script = '''
sh .bin/link.sh
cd dotfiles_private
make link
'''

[tasks.reload-tmux-conf]
script = '''
tmux source-file ~/.tmux.conf
'''
